// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx tsx prisma/seed.ts',
  },
  datasource: {
    // Use the direct (non-pooler) URL for migrations.
    // Neon's pooler (PgBouncer) doesn't support advisory locks which Prisma requires.
    // The runtime PrismaService uses DATABASE_URL (pooler) via PrismaPg adapter.
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
});
